version: 1
disable_existing_loggers: False

formatters:
    json:
        (): logging.JsonFormatter
        format: "%(asctime)s %(levelname)-7s - %(json)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: json
        stream: ext://sys.stdout

    json_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: json
        filename: barbante.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        delay: true

loggers:
    # scripts called from the command line
    __main__:
        level: INFO
        handlers: [json_file_handler]
        propagate: no

    barbante:
        level: INFO
        handlers: [json_file_handler]
        propagate: no

    barbante.utils.logging.trace:
        level: INFO
        handlers: [json_file_handler]
        propagate: no

    urllib3.connectionpool:
        level: INFO
        handlers: [json_file_handler]
        propagate: no

    tornado:
        level: WARN
        handlers: [json_file_handler]
        propagate: no

root:
    level: INFO
    handlers: [json_file_handler]
